### ISSUE TITLE
pyquaternion exists but can not be found.

### ISSUE THREAD

**Issue by xjtu19** [pietrolechthaler/UR5-Pick-and-Place-Simulation#11]
Everything seems ok until I run **rosrun motion_planning motion_planning.py**. The error is as follows:

> (tamp) xj@xj:~$ rosrun motion_planning motion_planning.py
Traceback (most recent call last):
  File "/home/xj/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 9, in <module>
    from controller import ArmController
  File "/home/xj/catkin_ws/src/motion_planning/scripts/controller.py", line 8, in <module>
    from pyquaternion import Quaternion
ModuleNotFoundError: No module named 'pyquaternion

Then I install the unfound package, but actually it's already installed:
> (tamp) xj@xj:~$ pip install pyquaternion
Requirement already satisfied: pyquaternion in ./anaconda3/envs/tamp/lib/python3.9/site-packages (0.9.9)
Requirement already satisfied: numpy in ./anaconda3/envs/tamp/lib/python3.9/site-packages (from pyquaternion) (1.26.4)

I also test it in python, this package can be imported.
>  (tamp) xj@xj:~$ python
Python 3.9.19 (main, Mar 21 2024, 17:11:28) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
import pyquaternion
from pyquaternion import Quaternion

Now I'm confused about why this happen and how to solve it. 
Thank you very much.

**Comment by xjtu19** [comment]
It's python version error. The default python version for ubuntu 20.04 is python3.8 in the /usr/bin/python3.8. Install pyquaternion and it works!
