### ISSUE TITLE
Motion planning controller issue

### ISSUE THREAD

**Issue by SpAlex01** [pietrolechthaler/UR5-Pick-and-Place-Simulation#8]
So I am trying to do this, and the gazebo starts fine, but then when I start the motion_planning.py script, it just stays at Initializing node of kinematics, and i stayed like that 10 minutes or so, and then when i close, it throws this.

Traceback (most recent call last):
  File "motion_planning.py", line 346, in <module>
    controller = ArmController()
  File "/home/odin/UR5-Pick-and-Place-Simulation/catkin_ws/src/motion_planning/scripts/controller.py", line 34, in __init__
    joint_states = get_controller_state(controller_topic).actual.positions
  File "/home/odin/UR5-Pick-and-Place-Simulation/catkin_ws/src/motion_planning/scripts/controller.py", line 12, in get_controller_state
    return rospy.wait_for_message(
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 428, in wait_for_message
    raise rospy.exceptions.ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown

I tried pressing play on gazebo, tried commenting the line with the ArmController(), but then it just stays at Initializing gripper controller.

**Comment by Dristi123** [comment]
Same issue!
